services:
  db:
    image: postgres
    container_name: database
    networks:
      - mainNetwork
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DBNAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
  redis:
    image: redis
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - mainNetwork
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

networks:
  mainNetwork:
    driver: bridge

volumes:
  db_data:
  redis_data: